var annotated_dup =
[
    [ "crl", "namespacecrl.html", [
      [ "gui", "namespacecrl_1_1gui.html", [
        [ "rendering", "namespacecrl_1_1gui_1_1rendering.html", [
          [ "MeshRenderingBuffer", "structcrl_1_1gui_1_1rendering_1_1_mesh_rendering_buffer.html", "structcrl_1_1gui_1_1rendering_1_1_mesh_rendering_buffer" ],
          [ "MeshRenderingContext", "structcrl_1_1gui_1_1rendering_1_1_mesh_rendering_context.html", "structcrl_1_1gui_1_1rendering_1_1_mesh_rendering_context" ],
          [ "RenderingContext", "structcrl_1_1gui_1_1rendering_1_1_rendering_context.html", "structcrl_1_1gui_1_1rendering_1_1_rendering_context" ],
          [ "TextureBuffer", "structcrl_1_1gui_1_1rendering_1_1_texture_buffer.html", "structcrl_1_1gui_1_1rendering_1_1_texture_buffer" ]
        ] ],
        [ "Application", "classcrl_1_1gui_1_1_application.html", "classcrl_1_1gui_1_1_application" ],
        [ "Light", "classcrl_1_1gui_1_1_light.html", "classcrl_1_1gui_1_1_light" ],
        [ "Line2D", "structcrl_1_1gui_1_1_line2_d.html", "structcrl_1_1gui_1_1_line2_d" ],
        [ "Lines", "classcrl_1_1gui_1_1_lines.html", "classcrl_1_1gui_1_1_lines" ],
        [ "Material", "structcrl_1_1gui_1_1_material.html", "structcrl_1_1gui_1_1_material" ],
        [ "Mesh", "classcrl_1_1gui_1_1_mesh.html", "classcrl_1_1gui_1_1_mesh" ],
        [ "Model", "classcrl_1_1gui_1_1_model.html", "classcrl_1_1gui_1_1_model" ],
        [ "MouseState", "classcrl_1_1gui_1_1_mouse_state.html", "classcrl_1_1gui_1_1_mouse_state" ],
        [ "RealTimeLinePlot2D", "classcrl_1_1gui_1_1_real_time_line_plot2_d.html", "classcrl_1_1gui_1_1_real_time_line_plot2_d" ],
        [ "Shader", "classcrl_1_1gui_1_1_shader.html", "classcrl_1_1gui_1_1_shader" ],
        [ "ShadowApplication", "classcrl_1_1gui_1_1_shadow_application.html", "classcrl_1_1gui_1_1_shadow_application" ],
        [ "ShadowCastingLight", "classcrl_1_1gui_1_1_shadow_casting_light.html", "classcrl_1_1gui_1_1_shadow_casting_light" ],
        [ "ShadowMapFBO", "classcrl_1_1gui_1_1_shadow_map_f_b_o.html", "classcrl_1_1gui_1_1_shadow_map_f_b_o" ],
        [ "SimpleGroundModel", "classcrl_1_1gui_1_1_simple_ground_model.html", "classcrl_1_1gui_1_1_simple_ground_model" ],
        [ "SizeableGroundModel", "classcrl_1_1gui_1_1_sizeable_ground_model.html", "classcrl_1_1gui_1_1_sizeable_ground_model" ],
        [ "Texture", "structcrl_1_1gui_1_1_texture.html", "structcrl_1_1gui_1_1_texture" ],
        [ "TrackingCamera", "classcrl_1_1gui_1_1_tracking_camera.html", "classcrl_1_1gui_1_1_tracking_camera" ],
        [ "Vertex", "structcrl_1_1gui_1_1_vertex.html", "structcrl_1_1gui_1_1_vertex" ]
      ] ],
      [ "loco", "namespacecrl_1_1loco.html", [
        [ "bFrameReferenceMotionPlan", "classcrl_1_1loco_1_1b_frame_reference_motion_plan.html", "classcrl_1_1loco_1_1b_frame_reference_motion_plan" ],
        [ "BipedalGaitPlanner", "classcrl_1_1loco_1_1_bipedal_gait_planner.html", "classcrl_1_1loco_1_1_bipedal_gait_planner" ],
        [ "BodyFrame", "classcrl_1_1loco_1_1_body_frame.html", "classcrl_1_1loco_1_1_body_frame" ],
        [ "ContactPhaseInfo", "classcrl_1_1loco_1_1_contact_phase_info.html", "classcrl_1_1loco_1_1_contact_phase_info" ],
        [ "ContactPlanManager", "classcrl_1_1loco_1_1_contact_plan_manager.html", "classcrl_1_1loco_1_1_contact_plan_manager" ],
        [ "ContactSchedule", "classcrl_1_1loco_1_1_contact_schedule.html", "classcrl_1_1loco_1_1_contact_schedule" ],
        [ "EndEffector", "classcrl_1_1loco_1_1_end_effector.html", "classcrl_1_1loco_1_1_end_effector" ],
        [ "FootstepPlan", "classcrl_1_1loco_1_1_footstep_plan.html", "classcrl_1_1loco_1_1_footstep_plan" ],
        [ "GaitPlanner", "classcrl_1_1loco_1_1_gait_planner.html", "classcrl_1_1loco_1_1_gait_planner" ],
        [ "GeneralizedCoordinatesRobotRepresentation", "classcrl_1_1loco_1_1_generalized_coordinates_robot_representation.html", "classcrl_1_1loco_1_1_generalized_coordinates_robot_representation" ],
        [ "IK_EndEffectorTargets", "structcrl_1_1loco_1_1_i_k___end_effector_targets.html", "structcrl_1_1loco_1_1_i_k___end_effector_targets" ],
        [ "IK_Solver", "classcrl_1_1loco_1_1_i_k___solver.html", "classcrl_1_1loco_1_1_i_k___solver" ],
        [ "JointState", "classcrl_1_1loco_1_1_joint_state.html", "classcrl_1_1loco_1_1_joint_state" ],
        [ "KinematicTrackingController", "classcrl_1_1loco_1_1_kinematic_tracking_controller.html", "classcrl_1_1loco_1_1_kinematic_tracking_controller" ],
        [ "LeggedRobot", "classcrl_1_1loco_1_1_legged_robot.html", "classcrl_1_1loco_1_1_legged_robot" ],
        [ "LimbMotionProperties", "classcrl_1_1loco_1_1_limb_motion_properties.html", "classcrl_1_1loco_1_1_limb_motion_properties" ],
        [ "LocomotionController", "classcrl_1_1loco_1_1_locomotion_controller.html", "classcrl_1_1loco_1_1_locomotion_controller" ],
        [ "LocomotionTrajectoryPlanner", "classcrl_1_1loco_1_1_locomotion_trajectory_planner.html", "classcrl_1_1loco_1_1_locomotion_trajectory_planner" ],
        [ "PeriodicGait", "classcrl_1_1loco_1_1_periodic_gait.html", "classcrl_1_1loco_1_1_periodic_gait" ],
        [ "PlannedLimbContact", "classcrl_1_1loco_1_1_planned_limb_contact.html", "classcrl_1_1loco_1_1_planned_limb_contact" ],
        [ "QuadrupedalGaitPlanner", "classcrl_1_1loco_1_1_quadrupedal_gait_planner.html", "classcrl_1_1loco_1_1_quadrupedal_gait_planner" ],
        [ "RB", "classcrl_1_1loco_1_1_r_b.html", "classcrl_1_1loco_1_1_r_b" ],
        [ "RB3DModel", "classcrl_1_1loco_1_1_r_b3_d_model.html", "classcrl_1_1loco_1_1_r_b3_d_model" ],
        [ "RBEndEffector", "classcrl_1_1loco_1_1_r_b_end_effector.html", "classcrl_1_1loco_1_1_r_b_end_effector" ],
        [ "RBEngine", "classcrl_1_1loco_1_1_r_b_engine.html", "classcrl_1_1loco_1_1_r_b_engine" ],
        [ "RBGlobals", "classcrl_1_1loco_1_1_r_b_globals.html", null ],
        [ "RBJoint", "classcrl_1_1loco_1_1_r_b_joint.html", "classcrl_1_1loco_1_1_r_b_joint" ],
        [ "RBLoader", "classcrl_1_1loco_1_1_r_b_loader.html", "classcrl_1_1loco_1_1_r_b_loader" ],
        [ "RBMaterial", "classcrl_1_1loco_1_1_r_b_material.html", "classcrl_1_1loco_1_1_r_b_material" ],
        [ "RBProperties", "classcrl_1_1loco_1_1_r_b_properties.html", "classcrl_1_1loco_1_1_r_b_properties" ],
        [ "RBRenderer", "classcrl_1_1loco_1_1_r_b_renderer.html", null ],
        [ "RBState", "structcrl_1_1loco_1_1_r_b_state.html", "structcrl_1_1loco_1_1_r_b_state" ],
        [ "Robot", "classcrl_1_1loco_1_1_robot.html", "classcrl_1_1loco_1_1_robot" ],
        [ "RobotLimb", "structcrl_1_1loco_1_1_robot_limb.html", "structcrl_1_1loco_1_1_robot_limb" ],
        [ "RobotState", "classcrl_1_1loco_1_1_robot_state.html", "classcrl_1_1loco_1_1_robot_state" ],
        [ "RRBCollisionBox", "classcrl_1_1loco_1_1_r_r_b_collision_box.html", "classcrl_1_1loco_1_1_r_r_b_collision_box" ],
        [ "RRBCollisionCapsule", "classcrl_1_1loco_1_1_r_r_b_collision_capsule.html", "classcrl_1_1loco_1_1_r_r_b_collision_capsule" ],
        [ "RRBCollisionCylinder", "classcrl_1_1loco_1_1_r_r_b_collision_cylinder.html", "classcrl_1_1loco_1_1_r_r_b_collision_cylinder" ],
        [ "RRBCollisionHeightMap", "classcrl_1_1loco_1_1_r_r_b_collision_height_map.html", "classcrl_1_1loco_1_1_r_r_b_collision_height_map" ],
        [ "RRBCollisionPlane", "classcrl_1_1loco_1_1_r_r_b_collision_plane.html", "classcrl_1_1loco_1_1_r_r_b_collision_plane" ],
        [ "RRBCollisionSphere", "classcrl_1_1loco_1_1_r_r_b_collision_sphere.html", "classcrl_1_1loco_1_1_r_r_b_collision_sphere" ],
        [ "RRBCollsionShape", "classcrl_1_1loco_1_1_r_r_b_collsion_shape.html", "classcrl_1_1loco_1_1_r_r_b_collsion_shape" ],
        [ "SimpleLocomotionTrajectoryPlanner", "classcrl_1_1loco_1_1_simple_locomotion_trajectory_planner.html", "classcrl_1_1loco_1_1_simple_locomotion_trajectory_planner" ],
        [ "SwingPhaseContainer", "classcrl_1_1loco_1_1_swing_phase_container.html", "classcrl_1_1loco_1_1_swing_phase_container" ]
      ] ],
      [ "GenericTrajectory", "classcrl_1_1_generic_trajectory.html", "classcrl_1_1_generic_trajectory" ],
      [ "key_word", "structcrl_1_1key__word.html", "structcrl_1_1key__word" ],
      [ "Logger", "classcrl_1_1_logger.html", "classcrl_1_1_logger" ],
      [ "P3D", "classcrl_1_1_p3_d.html", "classcrl_1_1_p3_d" ],
      [ "Plane", "classcrl_1_1_plane.html", "classcrl_1_1_plane" ],
      [ "Ray", "classcrl_1_1_ray.html", "classcrl_1_1_ray" ],
      [ "RigidTransformation", "classcrl_1_1_rigid_transformation.html", "classcrl_1_1_rigid_transformation" ],
      [ "Segment", "classcrl_1_1_segment.html", "classcrl_1_1_segment" ],
      [ "Timer", "classcrl_1_1_timer.html", "classcrl_1_1_timer" ],
      [ "V3D", "classcrl_1_1_v3_d.html", "classcrl_1_1_v3_d" ]
    ] ],
    [ "ImGui", "namespace_im_gui.html", [
      [ "FileBrowser", "class_im_gui_1_1_file_browser.html", "class_im_gui_1_1_file_browser" ]
    ] ],
    [ "ImGuizmo", "namespace_im_guizmo.html", [
      [ "Context", "struct_im_guizmo_1_1_context.html", "struct_im_guizmo_1_1_context" ],
      [ "matrix_t", "struct_im_guizmo_1_1matrix__t.html", "struct_im_guizmo_1_1matrix__t" ],
      [ "vec_t", "struct_im_guizmo_1_1vec__t.html", "struct_im_guizmo_1_1vec__t" ]
    ] ],
    [ "ImPlot", "namespace_im_plot.html", [
      [ "GetterError", "struct_im_plot_1_1_getter_error.html", "struct_im_plot_1_1_getter_error" ],
      [ "GetterFuncPtr", "struct_im_plot_1_1_getter_func_ptr.html", "struct_im_plot_1_1_getter_func_ptr" ],
      [ "GetterHeatmap", "struct_im_plot_1_1_getter_heatmap.html", "struct_im_plot_1_1_getter_heatmap" ],
      [ "GetterIdx", "struct_im_plot_1_1_getter_idx.html", "struct_im_plot_1_1_getter_idx" ],
      [ "GetterLin", "struct_im_plot_1_1_getter_lin.html", "struct_im_plot_1_1_getter_lin" ],
      [ "GetterOverrideX", "struct_im_plot_1_1_getter_override_x.html", "struct_im_plot_1_1_getter_override_x" ],
      [ "GetterOverrideY", "struct_im_plot_1_1_getter_override_y.html", "struct_im_plot_1_1_getter_override_y" ],
      [ "GetterRef", "struct_im_plot_1_1_getter_ref.html", "struct_im_plot_1_1_getter_ref" ],
      [ "GetterXs", "struct_im_plot_1_1_getter_xs.html", "struct_im_plot_1_1_getter_xs" ],
      [ "GetterXY", "struct_im_plot_1_1_getter_x_y.html", "struct_im_plot_1_1_getter_x_y" ],
      [ "ImPlotStyleVarInfo", "struct_im_plot_1_1_im_plot_style_var_info.html", "struct_im_plot_1_1_im_plot_style_var_info" ],
      [ "LineSegmentsRenderer", "struct_im_plot_1_1_line_segments_renderer.html", "struct_im_plot_1_1_line_segments_renderer" ],
      [ "LineStripRenderer", "struct_im_plot_1_1_line_strip_renderer.html", "struct_im_plot_1_1_line_strip_renderer" ],
      [ "MaxIdx", "struct_im_plot_1_1_max_idx.html", "struct_im_plot_1_1_max_idx" ],
      [ "RectInfo", "struct_im_plot_1_1_rect_info.html", "struct_im_plot_1_1_rect_info" ],
      [ "RectRenderer", "struct_im_plot_1_1_rect_renderer.html", "struct_im_plot_1_1_rect_renderer" ],
      [ "ShadedRenderer", "struct_im_plot_1_1_shaded_renderer.html", "struct_im_plot_1_1_shaded_renderer" ],
      [ "StairsRenderer", "struct_im_plot_1_1_stairs_renderer.html", "struct_im_plot_1_1_stairs_renderer" ],
      [ "TransformerLin", "struct_im_plot_1_1_transformer_lin.html", "struct_im_plot_1_1_transformer_lin" ],
      [ "TransformerLog", "struct_im_plot_1_1_transformer_log.html", "struct_im_plot_1_1_transformer_log" ],
      [ "TransformerXY", "struct_im_plot_1_1_transformer_x_y.html", "struct_im_plot_1_1_transformer_x_y" ]
    ] ],
    [ "locoApp", "namespaceloco_app.html", [
      [ "App", "classloco_app_1_1_app.html", "classloco_app_1_1_app" ],
      [ "ModelOption", "structloco_app_1_1_model_option.html", "structloco_app_1_1_model_option" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< crl::gui::Vertex >", "structstd_1_1hash_3_01crl_1_1gui_1_1_vertex_01_4.html", "structstd_1_1hash_3_01crl_1_1gui_1_1_vertex_01_4" ]
    ] ],
    [ "vg", "namespacevg.html", [
      [ "virtualGizmo3DClass", "classvg_1_1virtual_gizmo3_d_class.html", "classvg_1_1virtual_gizmo3_d_class" ],
      [ "virtualGizmoBaseClass", "classvg_1_1virtual_gizmo_base_class.html", "classvg_1_1virtual_gizmo_base_class" ],
      [ "virtualGizmoClass", "classvg_1_1virtual_gizmo_class.html", "classvg_1_1virtual_gizmo_class" ]
    ] ],
    [ "imguiGizmo", "structimgui_gizmo.html", "structimgui_gizmo" ],
    [ "ImPlotAlignmentData", "struct_im_plot_alignment_data.html", "struct_im_plot_alignment_data" ],
    [ "ImPlotAnnotation", "struct_im_plot_annotation.html", "struct_im_plot_annotation" ],
    [ "ImPlotAnnotationCollection", "struct_im_plot_annotation_collection.html", "struct_im_plot_annotation_collection" ],
    [ "ImPlotAxis", "struct_im_plot_axis.html", "struct_im_plot_axis" ],
    [ "ImPlotColormapData", "struct_im_plot_colormap_data.html", "struct_im_plot_colormap_data" ],
    [ "ImPlotContext", "struct_im_plot_context.html", "struct_im_plot_context" ],
    [ "ImPlotDateTimeFmt", "struct_im_plot_date_time_fmt.html", "struct_im_plot_date_time_fmt" ],
    [ "ImPlotInputMap", "struct_im_plot_input_map.html", "struct_im_plot_input_map" ],
    [ "ImPlotItem", "struct_im_plot_item.html", "struct_im_plot_item" ],
    [ "ImPlotItemGroup", "struct_im_plot_item_group.html", "struct_im_plot_item_group" ],
    [ "ImPlotLegend", "struct_im_plot_legend.html", "struct_im_plot_legend" ],
    [ "ImPlotNextItemData", "struct_im_plot_next_item_data.html", "struct_im_plot_next_item_data" ],
    [ "ImPlotNextPlotData", "struct_im_plot_next_plot_data.html", "struct_im_plot_next_plot_data" ],
    [ "ImPlotPlot", "struct_im_plot_plot.html", "struct_im_plot_plot" ],
    [ "ImPlotPoint", "struct_im_plot_point.html", "struct_im_plot_point" ],
    [ "ImPlotPointError", "struct_im_plot_point_error.html", "struct_im_plot_point_error" ],
    [ "ImPlotRange", "struct_im_plot_range.html", "struct_im_plot_range" ],
    [ "ImPlotRect", "struct_im_plot_rect.html", "struct_im_plot_rect" ],
    [ "ImPlotStyle", "struct_im_plot_style.html", "struct_im_plot_style" ],
    [ "ImPlotSubplot", "struct_im_plot_subplot.html", "struct_im_plot_subplot" ],
    [ "ImPlotTag", "struct_im_plot_tag.html", "struct_im_plot_tag" ],
    [ "ImPlotTagCollection", "struct_im_plot_tag_collection.html", "struct_im_plot_tag_collection" ],
    [ "ImPlotTick", "struct_im_plot_tick.html", "struct_im_plot_tick" ],
    [ "ImPlotTickCollection", "struct_im_plot_tick_collection.html", "struct_im_plot_tick_collection" ],
    [ "ImPlotTime", "struct_im_plot_time.html", "struct_im_plot_time" ]
];