var hierarchy =
[
    [ "crl::gui::Application", "classcrl_1_1gui_1_1_application.html", [
      [ "crl::gui::ShadowApplication", "classcrl_1_1gui_1_1_shadow_application.html", [
        [ "locoApp::App", "classloco_app_1_1_app.html", null ]
      ] ]
    ] ],
    [ "crl::loco::bFrameReferenceMotionPlan", "classcrl_1_1loco_1_1b_frame_reference_motion_plan.html", null ],
    [ "crl::loco::BodyFrame", "classcrl_1_1loco_1_1_body_frame.html", null ],
    [ "crl::Logger::ConsoleText", "structcrl_1_1_logger_1_1_console_text.html", null ],
    [ "crl::loco::ContactPhaseInfo", "classcrl_1_1loco_1_1_contact_phase_info.html", null ],
    [ "crl::loco::ContactPlanManager", "classcrl_1_1loco_1_1_contact_plan_manager.html", null ],
    [ "crl::loco::ContactSchedule", "classcrl_1_1loco_1_1_contact_schedule.html", null ],
    [ "ImGuizmo::Context", "struct_im_guizmo_1_1_context.html", null ],
    [ "crl::loco::EndEffector", "classcrl_1_1loco_1_1_end_effector.html", null ],
    [ "ImGui::FileBrowser", "class_im_gui_1_1_file_browser.html", null ],
    [ "crl::loco::FootstepPlan", "classcrl_1_1loco_1_1_footstep_plan.html", null ],
    [ "crl::loco::GaitPlanner", "classcrl_1_1loco_1_1_gait_planner.html", [
      [ "crl::loco::BipedalGaitPlanner", "classcrl_1_1loco_1_1_bipedal_gait_planner.html", null ],
      [ "crl::loco::QuadrupedalGaitPlanner", "classcrl_1_1loco_1_1_quadrupedal_gait_planner.html", null ]
    ] ],
    [ "crl::loco::GeneralizedCoordinatesRobotRepresentation", "classcrl_1_1loco_1_1_generalized_coordinates_robot_representation.html", null ],
    [ "crl::GenericTrajectory< T >", "classcrl_1_1_generic_trajectory.html", null ],
    [ "crl::GenericTrajectory< double >", "classcrl_1_1_generic_trajectory.html", null ],
    [ "crl::GenericTrajectory< V3D >", "classcrl_1_1_generic_trajectory.html", null ],
    [ "ImPlot::GetterError< T >", "struct_im_plot_1_1_getter_error.html", null ],
    [ "ImPlot::GetterFuncPtr", "struct_im_plot_1_1_getter_func_ptr.html", null ],
    [ "ImPlot::GetterHeatmap< T >", "struct_im_plot_1_1_getter_heatmap.html", null ],
    [ "ImPlot::GetterIdx< T >", "struct_im_plot_1_1_getter_idx.html", null ],
    [ "ImPlot::GetterLin", "struct_im_plot_1_1_getter_lin.html", null ],
    [ "ImPlot::GetterOverrideX< TGetter >", "struct_im_plot_1_1_getter_override_x.html", null ],
    [ "ImPlot::GetterOverrideY< TGetter >", "struct_im_plot_1_1_getter_override_y.html", null ],
    [ "ImPlot::GetterRef", "struct_im_plot_1_1_getter_ref.html", null ],
    [ "ImPlot::GetterXs< T >", "struct_im_plot_1_1_getter_xs.html", null ],
    [ "ImPlot::GetterXY< TGetterX, TGetterY >", "struct_im_plot_1_1_getter_x_y.html", null ],
    [ "std::hash< crl::gui::Vertex >", "structstd_1_1hash_3_01crl_1_1gui_1_1_vertex_01_4.html", null ],
    [ "crl::loco::IK_EndEffectorTargets", "structcrl_1_1loco_1_1_i_k___end_effector_targets.html", null ],
    [ "crl::loco::IK_Solver", "classcrl_1_1loco_1_1_i_k___solver.html", null ],
    [ "imguiGizmo", "structimgui_gizmo.html", null ],
    [ "ImPlotAlignmentData", "struct_im_plot_alignment_data.html", null ],
    [ "ImPlotAnnotation", "struct_im_plot_annotation.html", null ],
    [ "ImPlotAnnotationCollection", "struct_im_plot_annotation_collection.html", null ],
    [ "ImPlotAxis", "struct_im_plot_axis.html", null ],
    [ "ImPlotColormapData", "struct_im_plot_colormap_data.html", null ],
    [ "ImPlotContext", "struct_im_plot_context.html", null ],
    [ "ImPlotDateTimeFmt", "struct_im_plot_date_time_fmt.html", null ],
    [ "ImPlotInputMap", "struct_im_plot_input_map.html", null ],
    [ "ImPlotItem", "struct_im_plot_item.html", null ],
    [ "ImPlotItemGroup", "struct_im_plot_item_group.html", null ],
    [ "ImPlotLegend", "struct_im_plot_legend.html", null ],
    [ "ImPlotNextItemData", "struct_im_plot_next_item_data.html", null ],
    [ "ImPlotNextPlotData", "struct_im_plot_next_plot_data.html", null ],
    [ "ImPlotPlot", "struct_im_plot_plot.html", null ],
    [ "ImPlotPoint", "struct_im_plot_point.html", null ],
    [ "ImPlotPointError", "struct_im_plot_point_error.html", null ],
    [ "ImPlotRange", "struct_im_plot_range.html", null ],
    [ "ImPlotRect", "struct_im_plot_rect.html", null ],
    [ "ImPlotStyle", "struct_im_plot_style.html", null ],
    [ "ImPlot::ImPlotStyleVarInfo", "struct_im_plot_1_1_im_plot_style_var_info.html", null ],
    [ "ImPlotSubplot", "struct_im_plot_subplot.html", null ],
    [ "ImPlotTag", "struct_im_plot_tag.html", null ],
    [ "ImPlotTagCollection", "struct_im_plot_tag_collection.html", null ],
    [ "ImPlotTick", "struct_im_plot_tick.html", null ],
    [ "ImPlotTickCollection", "struct_im_plot_tick_collection.html", null ],
    [ "ImPlotTime", "struct_im_plot_time.html", null ],
    [ "crl::gui::Lines::iterator", "classcrl_1_1gui_1_1_lines_1_1iterator.html", null ],
    [ "crl::loco::JointState", "classcrl_1_1loco_1_1_joint_state.html", null ],
    [ "crl::key_word", "structcrl_1_1key__word.html", null ],
    [ "crl::gui::Light", "classcrl_1_1gui_1_1_light.html", [
      [ "crl::gui::ShadowCastingLight", "classcrl_1_1gui_1_1_shadow_casting_light.html", null ]
    ] ],
    [ "crl::loco::LimbMotionProperties", "classcrl_1_1loco_1_1_limb_motion_properties.html", null ],
    [ "crl::gui::Line2D< T >", "structcrl_1_1gui_1_1_line2_d.html", null ],
    [ "crl::gui::Lines", "classcrl_1_1gui_1_1_lines.html", null ],
    [ "ImPlot::LineSegmentsRenderer< TGetter1, TGetter2, TTransformer >", "struct_im_plot_1_1_line_segments_renderer.html", null ],
    [ "ImPlot::LineStripRenderer< TGetter, TTransformer >", "struct_im_plot_1_1_line_strip_renderer.html", null ],
    [ "crl::loco::LocomotionController", "classcrl_1_1loco_1_1_locomotion_controller.html", [
      [ "crl::loco::KinematicTrackingController", "classcrl_1_1loco_1_1_kinematic_tracking_controller.html", null ]
    ] ],
    [ "crl::loco::LocomotionTrajectoryPlanner", "classcrl_1_1loco_1_1_locomotion_trajectory_planner.html", [
      [ "crl::loco::SimpleLocomotionTrajectoryPlanner", "classcrl_1_1loco_1_1_simple_locomotion_trajectory_planner.html", null ]
    ] ],
    [ "crl::Logger", "classcrl_1_1_logger.html", null ],
    [ "crl::gui::Material", "structcrl_1_1gui_1_1_material.html", null ],
    [ "ImGuizmo::matrix_t", "struct_im_guizmo_1_1matrix__t.html", null ],
    [ "ImPlot::MaxIdx< T >", "struct_im_plot_1_1_max_idx.html", null ],
    [ "crl::gui::Mesh", "classcrl_1_1gui_1_1_mesh.html", null ],
    [ "crl::gui::rendering::MeshRenderingBuffer", "structcrl_1_1gui_1_1rendering_1_1_mesh_rendering_buffer.html", null ],
    [ "crl::gui::rendering::MeshRenderingContext", "structcrl_1_1gui_1_1rendering_1_1_mesh_rendering_context.html", null ],
    [ "crl::gui::Model", "classcrl_1_1gui_1_1_model.html", [
      [ "crl::loco::RB3DModel", "classcrl_1_1loco_1_1_r_b3_d_model.html", null ]
    ] ],
    [ "locoApp::ModelOption", "structloco_app_1_1_model_option.html", null ],
    [ "crl::gui::MouseState", "classcrl_1_1gui_1_1_mouse_state.html", null ],
    [ "crl::P3D", "classcrl_1_1_p3_d.html", null ],
    [ "crl::loco::PeriodicGait", "classcrl_1_1loco_1_1_periodic_gait.html", null ],
    [ "crl::Plane", "classcrl_1_1_plane.html", null ],
    [ "crl::loco::PlannedLimbContact", "classcrl_1_1loco_1_1_planned_limb_contact.html", null ],
    [ "crl::Ray", "classcrl_1_1_ray.html", null ],
    [ "crl::loco::RB", "classcrl_1_1loco_1_1_r_b.html", null ],
    [ "crl::loco::RBEndEffector", "classcrl_1_1loco_1_1_r_b_end_effector.html", null ],
    [ "crl::loco::RBEngine", "classcrl_1_1loco_1_1_r_b_engine.html", null ],
    [ "crl::loco::RBGlobals", "classcrl_1_1loco_1_1_r_b_globals.html", null ],
    [ "crl::loco::RBJoint", "classcrl_1_1loco_1_1_r_b_joint.html", null ],
    [ "crl::loco::RBLoader", "classcrl_1_1loco_1_1_r_b_loader.html", null ],
    [ "crl::loco::RBMaterial", "classcrl_1_1loco_1_1_r_b_material.html", null ],
    [ "crl::loco::RBProperties", "classcrl_1_1loco_1_1_r_b_properties.html", null ],
    [ "crl::loco::RBRenderer", "classcrl_1_1loco_1_1_r_b_renderer.html", null ],
    [ "crl::loco::RBState", "structcrl_1_1loco_1_1_r_b_state.html", null ],
    [ "crl::gui::RealTimeLinePlot2D< T >", "classcrl_1_1gui_1_1_real_time_line_plot2_d.html", null ],
    [ "ImPlot::RectInfo", "struct_im_plot_1_1_rect_info.html", null ],
    [ "ImPlot::RectRenderer< TGetter, TTransformer >", "struct_im_plot_1_1_rect_renderer.html", null ],
    [ "crl::gui::rendering::RenderingContext", "structcrl_1_1gui_1_1rendering_1_1_rendering_context.html", null ],
    [ "crl::RigidTransformation", "classcrl_1_1_rigid_transformation.html", null ],
    [ "crl::loco::Robot", "classcrl_1_1loco_1_1_robot.html", [
      [ "crl::loco::LeggedRobot", "classcrl_1_1loco_1_1_legged_robot.html", null ]
    ] ],
    [ "crl::loco::RobotLimb", "structcrl_1_1loco_1_1_robot_limb.html", null ],
    [ "crl::loco::RobotState", "classcrl_1_1loco_1_1_robot_state.html", null ],
    [ "crl::loco::RRBCollsionShape", "classcrl_1_1loco_1_1_r_r_b_collsion_shape.html", [
      [ "crl::loco::RRBCollisionBox", "classcrl_1_1loco_1_1_r_r_b_collision_box.html", null ],
      [ "crl::loco::RRBCollisionCapsule", "classcrl_1_1loco_1_1_r_r_b_collision_capsule.html", null ],
      [ "crl::loco::RRBCollisionCylinder", "classcrl_1_1loco_1_1_r_r_b_collision_cylinder.html", null ],
      [ "crl::loco::RRBCollisionHeightMap", "classcrl_1_1loco_1_1_r_r_b_collision_height_map.html", null ],
      [ "crl::loco::RRBCollisionPlane", "classcrl_1_1loco_1_1_r_r_b_collision_plane.html", null ],
      [ "crl::loco::RRBCollisionSphere", "classcrl_1_1loco_1_1_r_r_b_collision_sphere.html", null ]
    ] ],
    [ "crl::Segment", "classcrl_1_1_segment.html", null ],
    [ "ImPlot::ShadedRenderer< TGetter1, TGetter2, TTransformer >", "struct_im_plot_1_1_shaded_renderer.html", null ],
    [ "crl::gui::Shader", "classcrl_1_1gui_1_1_shader.html", null ],
    [ "crl::gui::ShadowMapFBO", "classcrl_1_1gui_1_1_shadow_map_f_b_o.html", null ],
    [ "crl::gui::SimpleGroundModel", "classcrl_1_1gui_1_1_simple_ground_model.html", null ],
    [ "crl::gui::SizeableGroundModel", "classcrl_1_1gui_1_1_sizeable_ground_model.html", null ],
    [ "ImPlot::StairsRenderer< TGetter, TTransformer >", "struct_im_plot_1_1_stairs_renderer.html", null ],
    [ "crl::loco::SwingPhaseContainer", "classcrl_1_1loco_1_1_swing_phase_container.html", null ],
    [ "crl::gui::Texture", "structcrl_1_1gui_1_1_texture.html", null ],
    [ "crl::gui::rendering::TextureBuffer", "structcrl_1_1gui_1_1rendering_1_1_texture_buffer.html", null ],
    [ "crl::Timer", "classcrl_1_1_timer.html", null ],
    [ "crl::gui::TrackingCamera", "classcrl_1_1gui_1_1_tracking_camera.html", null ],
    [ "ImPlot::TransformerLin", "struct_im_plot_1_1_transformer_lin.html", null ],
    [ "ImPlot::TransformerLog", "struct_im_plot_1_1_transformer_log.html", null ],
    [ "ImPlot::TransformerXY< TransformerX, TransformerY >", "struct_im_plot_1_1_transformer_x_y.html", null ],
    [ "ImGuizmo::vec_t", "struct_im_guizmo_1_1vec__t.html", null ],
    [ "Vector3d", null, [
      [ "crl::V3D", "classcrl_1_1_v3_d.html", null ]
    ] ],
    [ "crl::gui::Vertex", "structcrl_1_1gui_1_1_vertex.html", null ],
    [ "VGIZMO_BASE_CLASS", null, [
      [ "vg::virtualGizmo3DClass", "classvg_1_1virtual_gizmo3_d_class.html", null ],
      [ "vg::virtualGizmoClass", "classvg_1_1virtual_gizmo_class.html", null ]
    ] ],
    [ "vg::virtualGizmoBaseClass", "classvg_1_1virtual_gizmo_base_class.html", null ]
];